config/routes.rb
Indiependency::Application.routes.draw do
  resources :games

  get "static_pages/about"
  root "static_pages#home"
  get "/help" => "static_pages#help"
  devise_for :users

  

  

end

app/models/game.rb
class Game < ActiveRecord::Base
	acts_as_votable
	# has_attached_file :game_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	# validates :game_image, :attachment_presence => true
	validates_presence_of  :description
	validates :title, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
    	:recoverable, :rememberable, :trackable, :validatable
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  	validates :email, format: { with: VALID_EMAIL_REGEX }
    acts_as_voter

    validates_presence_of :fullName, :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception



  # def devise_parameter_sanitizer
  # 	if resource_class == User
  # 		User::ParameterSanitizer.new(User, :user, params)
  # 	else
  # 		super
  # 	end
  # end

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:fullName, :country, :email, :password, :password_confirmation) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:fullName, :country, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :video_url, :facebook_url, :twitter_url, :web_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br>
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :facebook_url %><br>
    <%= f.text_field :facebook_url %>
  </div>
  <div class="field">
    <%= f.label :twitter_url %><br>
    <%= f.text_field :twitter_url %>
  </div>
  <div class="field">
    <%= f.label :web_url %><br>
    <%= f.text_field :web_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Video url</th>
      <th>Facebook url</th>
      <th>Twitter url</th>
      <th>Web url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.description %></td>
        <td><%= game.video_url %></td>
        <td><%= game.facebook_url %></td>
        <td><%= game.twitter_url %></td>
        <td><%= game.web_url %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @game.video_url %>
</p>

<p>
  <strong>Facebook url:</strong>
  <%= @game.facebook_url %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @game.twitter_url %>
</p>

<p>
  <strong>Web url:</strong>
  <%= @game.web_url %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Indiependency</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    <!-- Bootstrap core CSS -->

  </head>

  <body>

    <!-- Side Menu -->
    <a id="menu-toggle" href="#" class="btn btn-primary btn-lg toggle"><i class="icon-reorder"></i></a>
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-default btn-lg pull-right toggle"><i class="icon-remove"></i></a>
        <li class="sidebar-brand"><%= link_to "Indiependency", root_path, method: :get %></li>
        <% if user_signed_in? %>
        <li class="active"><a href="#">Bienvenido <%= current_user.fullName %></a></li>
        <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
        <% else %>  
        <li><%= link_to "Log In", new_user_session_path, method: :get %></li>
        
        <% end %>
        <li><%= link_to "Game Showcase", games_path, method: :get %></li>
        <li><a href="#">Home</a></li>
        <li><a href="#">Portfolio</a></li>
        <li><a href="#">Services</a></li>
        <li><%= link_to "Need Help?", help_path, method: :get %></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <canvas id="clockid" class="CoolClock:modern:70" style="position:absolute; bottom:0; left:25%"></canvas>
    </div>
    <!-- /Side Menu -->
  

<!--      <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p> -->
     <%= yield %>


  <!-- Custom JavaScript for the Side Menu - Put in a custom JS file if you want to clean this up -->
  <script>
      $("#menu-close").click(function(e) {
          e.preventDefault();
          $("#sidebar-wrapper").toggleClass("active");
      });
  </script>
  <script>
      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#sidebar-wrapper").toggleClass("active");
      });
  </script>

  </body>

</html>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>This is the Help section!</p>

app/views/static_pages/home.html.erb
    <!-- Full Page Image Header Area -->
    <div class="header">
      <div class="vert-text">
        <h1>Thank You!</h1>
        <h3><em>We</em> Build Great Templates, <em>You</em> Make Them Better</h3>
        <a href="#intro" class="btn btn-default btn-lg">Find Out More</a>
      </div>
    </div>
    <!-- /Full Page Image Header Area -->
  
    <!-- Intro -->
    <div id="intro" class="intro">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h2>Subtle Sidebar is the Perfect Template for your Next Portfolio Website Project!</h2>
            <p class="lead">This template really has it all. It's up to you to customize it to your liking! It features some fresh photography courtesy of <a target="_blank" href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a>.</p>
          </div>
        </div>
      </div>
    </div>
    <!-- /Intro -->
  
    <!-- Services -->
    <div class="services">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>Our Services</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2 col-md-offset-2 text-center">
            <div class="service-item">
              <i class="service-icon icon-rocket"></i>
              <h4>Spacecraft Repair</h4>
              <p>Did your navigation system shut down in the middle of that asteroid field? We can repair any dings and scrapes to your spacecraft!</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <i class="service-icon icon-magnet"></i>
              <h4>Problem Solving</h4>
              <p>Need to know how magnets work? Our problem solving solutions team can help you identify problems and conduct exploratory research.</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <i class="service-icon icon-shield"></i>
              <h4>Blacksmithing</h4>
              <p>Planning a time travel trip to the middle ages? Preserve the space time continuum by blending in with period accurate armor and weapons.</p>
            </div>
          </div>
          <div class="col-md-2 text-center">
            <div class="service-item">
              <i class="service-icon icon-pencil"></i>
              <h4>Pencil Sharpening</h4>
              <p>We've been voted the best pencil sharpening service for 10 consecutive years. If you have a pencil that feels dull, we'll get it sharp!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Services -->

    <!-- Callout -->
    <div class="callout">
      <div class="vert-text">
        <h1>A Dramatic Text Area</h1>
      </div>
    </div>
    <!-- /Callout -->

    <!-- Portfolio -->
    <div class="portfolio">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4 text-center">
            <h2>Our Work</h2>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-2 text-center">
            <div class="portfolio-item">
              <a href="#"><img class="img-portfolio img-responsive" src="/assets/portfolio-1.jpg"></a>
              <h4>Cityscape</h4>
            </div>
          </div>
          <div class="col-md-4 text-center">
            <div class="portfolio-item">
              <a href="#"><img class="img-portfolio img-responsive" src="/assets/portfolio-2.jpg"></a>
              <h4>Is That On Fire?</h4>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-2 text-center">
            <div class="portfolio-item">
              <a href="#"><img class="img-portfolio img-responsive" src="/assets/portfolio-3.jpg"></a>
              <h4>Stop Sign</h4>
            </div>
          </div>
          <div class="col-md-4 text-center">
            <div class="portfolio-item">
              <a href="#"><img class="img-portfolio img-responsive" src="/assets/portfolio-4.jpg"></a>
              <h4>Narrow Focus</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Portfolio -->

    <!-- Call to Action -->
    <div class="call-to-action">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <h3>The buttons below are impossible to resist.</h3>
            <a href="#" class="btn btn-lg btn-default">Click Me!</a>
            <a href="#" class="btn btn-lg btn-primary">Look at Me!</a>
          </div>
        </div>
      </div>
    </div>
    <!-- /Call to Action -->

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 text-center">
            <ul class="list-inline">
              <li><i class="icon-facebook icon-2x"></i></li>
              <li><i class="icon-twitter icon-2x"></i></li>
              <li><i class="icon-dribbble icon-2x"></i></li>
            </ul>
            <hr>
            <p>Copyright &copy; Company 2013</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- /Footer -->

    <div id="preload" style="display:none">
       <img src="assets/bg-day.jpg" width="1" height="1" alt="Image 01" />
       <img src="assets/bg-afternoon.jpg" width="1" height="1" alt="Image 02" />
       <img src="assets/bg-night.jpg" width="1" height="1" alt="Image 03" />
    </div>